service: blogger
image:  myanch200/blogger

servers:
  web:
    - 37.27.12.123

registry:
  username: myanch200
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 65.21.188.160
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:15
    host: 65.21.188.160
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'blogger'
        POSTGRES_DB: 'blogger_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data