service: blogger
image:  myanch200/blogger

servers:
  web:
    - 195.201.3.254

registry:
  username: myanch200
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 116.203.37.171
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:15
    host: 116.203.37.171
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'blogger'
        POSTGRES_DB: 'blogger_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data